### ISSUE TITLE
Library license?

### ISSUE THREAD

**Issue by rjahn** [DJ-Raven/java-swing-ui-chat-messenger#1]
Your project contains the library: [gradient-icon-font.jar](https://github.com/DJ-Raven/java-swing-ui-chat-messenger/blob/main/lib/gradient-icon-font.jar)

Do you have an official download link/repository or the license for the library?

**Comment by DJ-Raven** [comment]
Here it's free to use [link](https://github.com/DJ-Raven/gradient-icon-font)

**Comment by rjahn** [comment]
The linked project is without license. This is a problem and it can‘t be bundled. 

Some classes look exactly like jiconfont but without license and javadoc?
Anyway, a license like Apache 2.0 or MIT would be nice.

**Comment by DJ-Raven** [comment]
I have added

**Comment by rjahn** [comment]
Great.

Sorry, but you should add a license header to your source files as well 😬.

The license for the repository does not apply to single files if other developers use your files.

**Comment by rjahn** [comment]
I guess your problem with license header is that most code is copied from other libraries like jiconfont or stackoverflow articles. Most code pieces are copied 1:1.

In this case, this repo contains useful code but can't be used from other developers.
